name: GLaDOS-Signin
 
on:
  workflow_dispatch:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    # `0 23 * * *` 表示UTC 23:00，即北京时间7:00打卡（经测试，实际运行时间比设定时间晚几分钟到几十分钟）。
    # 可以参考 https://crontab.guru/ 进行配置
    # 每8h重复执行一次，防止打卡失败
    - cron: 0 */8 * * *

jobs:
  GLaDOS-Signin:
    runs-on: ubuntu-latest
    env:
      USE_SMTP: ${{ secrets.USE_SMTP }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
      USE_SERVER: ${{ secrets.USE_SERVER }}
      USE_TELEGRAM: ${{ secrets.USE_TELEGRAM }}
      PUSHPLUS_SERVER: ${{ secrets.PUSHPLUS_SERVER }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set script permissions
        run: chmod +x signin.sh
      
      - name: signin
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          OUTPUT=$(./signin.sh "$COOKIE")
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
          echo "$OUTPUT"

      - name: Send mail [Optional]
        if: env.USE_SMTP == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ env.SMTP_SERVER }}
          server_port: ${{ env.SMTP_PORT }}
          username: ${{ env.SMTP_USERNAME }}
          password: ${{ env.SMTP_PASSWORD }}
          subject: GLaDOS 每日签到
          to: ${{ env.SMTP_RECEIVER }}
          from: ${{ env.SMTP_USERNAME }}
          body: ${{ env.OUTPUT }}

      - name: ServerChan [Optional]
        if: env.USE_SERVER == 'true'
        uses: easychen/github-action-server-chan@v1.0.0
        with:
          sendkey: ${{ secrets.SENDKEY }}
          title: "🚀 Glados-Signin Notification"
          desp: ${{ env.OUTPUT }}
          
      - name: TelegramBot [Optional]
        if: env.USE_TELEGRAM == 'true'
        uses: appleboy/telegram-action@master
        with:
          token: 6401388840:AAEpl78y2DgzLL_JX5msJVovR2ALMq2WzP4
          to: ${{ secrets.ChatID }}
          message: "🚀 Glados-Signin Notification\n${{ env.OUTPUT }}"

      - name: PUSHPLUS [Optional]
        if: env.PUSHPLUS_SERVER == 'true'
        uses: xhnmt/pushplus-action@v1.0.0
        with:
          token: ${{ secrets.PUSHPLUS_TOKEN }}
          title: "🚀 Glados-Signin Notification"
          content: ${{ env.OUTPUT }}
